### ISSUE TITLE
Install Attempts Fail

### ISSUE THREAD

**Issue by brimwats1** [YunoHost-Apps/metabase_ynh#2]
Tried installing through the webadmin and get the following error: Could not fetch sources files, is the URL correct?

**Comment by ColinMaudry** [comment]
It worked for me through the command line, deploying the testing branch:

```
yunohost app install https://github.com/YunoHost-Apps/metabase_ynh/tree/testing
```

**Comment by ColinMaudry** [comment]
I have merged `testing` into `main`: could you please retry with the main branch:

https://github.com/YunoHost-Apps/metabase_ynh

**Comment by brimwats1** [comment]
> I have merged `testing` into `main`: could you please retry with the main branch:
> 
> https://github.com/YunoHost-Apps/metabase_ynh

I am trying via webadmin and it is still giving me `Could not fetch sources files, is the URL correct?`

Should I try via CLI? Main or testing branch?

**Comment by ColinMaudry** [comment]
@brimwats Please use https://github.com/YunoHost-Apps/metabase_ynh/tree/testing, on webadmin or CLI, as you prefer. I tested it successfully on CLI, but there should be no difference in webadmin.

`main` and `testing` are now identical, but on `main` the installation still returns:

> Could not fetch sources files, is the URL correct?

@ericgaspar is there some caching on client side that would explain this difference?

**Comment by brimwats1** [comment]
I tried installing:

```
Info: Installing metabase...
Info: [....................] > Validating installation parameters...
Info: [+++.................] > Finding an available port...
Info: [###.................] > Installing dependencies...
Info: [###++++.............] > Creating a PostgreSQL database...
Info: [#######++...........] > Setting up source files...
Info: [#########++.........] > Configuring NGNX web server...
Info: [###########++.......] > Configuring system user...
Info: [#############.......] > Configuring a systemd service...
Info: [#############+++....] > Integrating service in YunoHost...
Info: [################+...] > Starting a systemd service...
Info: [#################+..] > Configuring permissions...
Info: [##################+.] > Reloading NGINX web server...
Success! Installation completed
```

On trying to access it (metabase.domain.tld) I get a 502 Bad Gateway / nginx error

**Comment by brimwats1** [comment]
I spoke too soon! It works fine now. How do I switch to main branch from testing?

**Comment by ColinMaudry** [comment]
It won't update automatically and the update routine is not in place, so the branch you use for installation doesn't matter once it's installed.

If you want to upgrade Metabase and the update hasn't already been added here, you can follow the instructions [to upgrade the JAR file](https://www.metabase.com/docs/latest/operations-guide/upgrading-metabase.html#jar-file).

The latest JAR is here: https://www.metabase.com/start/oss/jar.html
